# Numpy

## 1D ARRAY

In [4]:
import numpy as np

In [5]:
a = np.array([1,2,3],dtype=float)

In [6]:
a

array([1., 2., 3.])

In [7]:
print(a)

[1. 2. 3.]


## 2D ARRAY

In [10]:
b = np.array([[1,2],[3,4],[5,6],[7,8]])

In [11]:
print(b)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


## 3D ARRAY

In [14]:
c = np.array([[[1,2],[3,4]],[[5,6,],[7,8]]])

In [15]:
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Attributes:

In [18]:
print(a)
print(a.size)
print(a.ndim)
print(a.itemsize)
print(a.dtype)
print(a.shape)

[1. 2. 3.]
3
1
8
float64
(3,)


In [19]:
print(b)
print(b.size)
print(b.ndim)
print(b.itemsize)
print(b.dtype)
print(b.shape)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
8
2
8
int64
(4, 2)


In [20]:
print(c)
print(c.size)
print(c.ndim)
print(c.itemsize)
print(c.dtype)
print(c.shape)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
8
3
8
int64
(2, 2, 2)


### np.arange

In [23]:
d = np.arange(7)
d

array([0, 1, 2, 3, 4, 5, 6])

In [24]:
d = np.arange(3,7)
d

array([3, 4, 5, 6])

In [25]:
d = np.arange(1,8,3)

In [26]:
d

array([1, 4, 7])

In [28]:
d = np.linspace(1,10,10)   #not in syllabus

d

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

### Arithmetic operations

In [29]:
a

array([1., 2., 3.])

In [30]:
print(a*3)
print(a**3)
print(a/3)
print(a//3)
print(a + 3)
print(a - 3)

[3. 6. 9.]
[ 1.  8. 27.]
[0.33333333 0.66666667 1.        ]
[0. 0. 1.]
[4. 5. 6.]
[-2. -1.  0.]


### Reshape
- It changes the dimension of the given array

In [31]:
a = np.array([1,2,3,4,5,6,7,8,9,10,11,12]).reshape(3,4)

In [32]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [37]:
np.arange(1,13).reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [38]:
a = np.array([1,2,3,4,5,6,7,8,9,10,11,12]).reshape(2,3,2)

In [39]:
a

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [40]:
a = np.array([1,2,3,4,5,6,7,8,9,10,11,12]).reshape(1,6,2)

In [41]:
a

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [42]:
a = np.array([1,2,3,4,5,6,7,8,9,10,11,12]).reshape(4,3,1)

In [43]:
a

array([[[ 1],
        [ 2],
        [ 3]],

       [[ 4],
        [ 5],
        [ 6]],

       [[ 7],
        [ 8],
        [ 9]],

       [[10],
        [11],
        [12]]])

## Numpy nditer

In [44]:
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [45]:
for i in c:
    print(i)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [46]:
for i in c:
    for j in i:
        print(j)

[1 2]
[3 4]
[5 6]
[7 8]


In [47]:
for i in c:
    for j in i:
        for k in j:
            print(k)

1
2
3
4
5
6
7
8


In [50]:
for i in np.nditer(c):
    print(i)

1
2
3
4
5
6
7
8


## Ndenumerate

In [51]:
for i,v in np.ndenumerate(c):
    print("Index-",i,"Value - ",v)

Index- (0, 0, 0) Value -  1
Index- (0, 0, 1) Value -  2
Index- (0, 1, 0) Value -  3
Index- (0, 1, 1) Value -  4
Index- (1, 0, 0) Value -  5
Index- (1, 0, 1) Value -  6
Index- (1, 1, 0) Value -  7
Index- (1, 1, 1) Value -  8


## `np.concatenate`
- It is used to join two arrays along the axis

In [52]:
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)
print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [53]:
np.concatenate((c,d),axis = 0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [54]:
np.concatenate((c,d),axis = 1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

In [55]:
np.concatenate((c,d),axis = 2)  #Throws error - inconsistent dimension

AxisError: axis 2 is out of bounds for array of dimension 2

## Array split
- It is opposite to join function
- It splits the given array based on the split criteria
- For an array of length l that should be split into n sections, it return l % n sub-arrays of size 

In [56]:
np.array_split??

Signature:       np.array_split(ary, indices_or_sections, axis=0)
Call signature:  np.array_split(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <function array_split at 0x000002503E2E5C60>
File:            e:\anaconda\lib\site-packages\numpy\lib\_shape_base_impl.py
Source:         
@array_function_dispatch(_array_split_dispatcher)
def array_split(ary, indices_or_sections, axis=0):
    """
    Split an array into multiple sub-arrays.

    Please refer to the ``split`` documentation.  The only difference
    between these functions is that ``array_split`` allows
    `indices_or_sections` to be an integer that does *not* equally
    divide the axis. For an array of length l that should be split
    into n sections, it returns l % n sub-arrays of size l//n + 1
    and the rest of size l//n.

    See Also
    --------
    split : Split array into multiple sub-arrays of equal size.

    Examples
    --------
    >>> import numpy as np
    >>> x = np.arange(8.0)


In [61]:
np.array_split(2)

TypeError: array_split() missing 1 required positional argument: 'indices_or_sections'

In [58]:
a = np.arange(8)
a

array([0, 1, 2, 3, 4, 5, 6, 7])

In [60]:
np.array_split(a,5)

[array([0, 1]), array([2, 3]), array([4, 5]), array([6]), array([7])]

## `np.where`
- It returns the indices of elements of an input array where the given condition is satisfied

In [62]:
a = np.array([45,34,55,12,87,34,25,93])

In [63]:
np.where(a>50)

(array([2, 4, 7]),)

In [65]:
np.where(a>50,0,a)

array([45, 34,  0, 12,  0, 34, 25,  0])

In [66]:
np.where(a % 2 == 0,0,a)

array([45,  0, 55,  0, 87,  0, 25, 93])

### WAP to return array of items by taking the third coloumn from all the rows

In [67]:
sa = np.array([[11,22,33],[44,55,66],[77,88,99]])

In [70]:
for i in sa:
    print(i[-1])

33
66
99


In [71]:
sa[:,2]

array([33, 66, 99])

### For a given numpy array = [0,12,45.21,34.99,99.91,32] convert to celsius value sort the array and find the pos at 0

In [75]:
f = np.array([0,12,45.21,34.99,99.91,32])
c = (f-32) *(5/9)
print(c)
sc = np.sort(c)  #sort the array

[-17.77777778 -11.11111111   7.33888889   1.66111111  37.72777778
   0.        ]


In [76]:
sc

array([-17.77777778, -11.11111111,   0.        ,   1.66111111,
         7.33888889,  37.72777778])

In [78]:
np.where(sc==0)

(array([2]),)

## Swap the coloumn

In [79]:
a = np.array([[0,1,2,3],[4,5,6,7],[8,9,10,11]])
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [80]:
a[:,[0,1]]=a[:,[1,0]]
a

array([[ 1,  0,  2,  3],
       [ 5,  4,  6,  7],
       [ 9,  8, 10, 11]])

## Sorting

In [84]:
arr = np.array([[3,2,4],[5,0,1]])
arr

array([[3, 2, 4],
       [5, 0, 1]])

In [85]:
print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


In [86]:
print(np.sort(arr,axis = 0))

[[3 0 1]
 [5 2 4]]


In [87]:
print(np.sort(arr,axis = 1))

[[2 3 4]
 [0 1 5]]
